### ISSUE TITLE
[Bug]: Fix React Examples

### ISSUE THREAD

**Issue by satyambnsal** [dojoengine/dojo.js#105]
### Dojo.js Version

0.2.10

### What happened?

**DojoProvider** usage in both react examples is incorrect. Also generate component script is using incorrect `dojo-starter` path.

### What is the expected behavior?

Should provide **world address** as a first argument in **DojoProvider**

### Steps to reproduce

Run any of the react example

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by rsodre** [comment]
Trying to update my games to the new examples, but will give up for now due to inconsistencies and lack of upgrade instructions

Some more notes on the react-app example...

* still importing packages version `0.2.10`, instead of the latest `0.3.3`
* there's a new `src/dojo/generated/' but no task to build it. Please explain how we should use it.
* the`create-components` task will not work because of the new folder structure
* shouldn't all graphql stuff be removed by now?

**Comment by ponderingdemocritus** [comment]
fixed in #104
