### ISSUE TITLE
Typed torii-client abstractions and query API

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo.js#154]
**Background**

Torii-client currently exposes functions to fetch from torii-server. Right now they are low level abstractions, we can improve these to make it very easy for any js app to sync or fetch with a remote torii.

Right now we sync the entire of the world state onload, and also when state changes these are reflected. This is great for prototyping however when applications become more complex and the state grows the whole application and UX slows because of this.

We can provide a clean abstraction for users to query the state allowing for extremely effiecent apps.

**Tasks**
This task is to build pure JS abstractions within the torii-client package which can then be used upstream in react or other frameworks.

**Comment by RareSecond** [comment]
Here's my suggestion for the interface. Examples below are based on the Dojo starter.

## Fetching a single entity

If you only want a single entity, you should be able to query the model directly.

```ts
const move = dojo.moves.find({
  where: {
    player: "0x0"
  }
}
```

This will strongly type the `move` variable as an instance of Moves. The `where` query should also be typed.

```ts
const move: Moves | undefined;
```

```ts
(property) where: {
  player?: string;
  remaining?: number;
  last_direction?: Direction;
}
```

## Fetching multiple entities from the same model

```ts
const moves = dojo.moves.findMany({
  where: {
    remaining: 0
  }
}
```

Same as before, `moves` will be strongly typed, just like the `where` query.

```ts
const moves: Array<Moves>;
```

## Fetching multiple entities from different models

```ts
const entities = dojo.findEntities(
  {
    where: {
      player: "0x0",
    },
  },
  [Models.Moves, Models.Position]
);
```

The resulting `entities` array will by typed by being an array of `Moves` and `Position` elements. Consumers can differentiate by checking the added `__modelName` on the entity. Or we could also export a typeguard for every model so that it can be checked that way.

```ts
const move: Array<Moves | Position>;
```

## Executing a call

Executing functions should also be strongly typed, to have the best DX.

Again, for the Dojo starter, this should result in the code below being valid (and fully typed)

```ts
await dojo.actions.spawn("0x0");

await dojo.actions.move("0x0", [Directions.Up]);
```

**Comment by tarrencev** [comment]
This generally looks good!

One concern is with the namespacing of the models / contracts (resources). Attaching `actions` and `moves` directly to the dojo namespace will cause issues when there are multiple resourceswith the same name.

At the dojo level, we are working towards namespacing resources using the fully qualified url.

For example,

```rust
dojo_examples::models::moves
dojo_examples::actions::actions
```

Then a different project could have the same resource names:

```rust
other_project::models::moves
other_project::actions::actions
```

We should have a generic base api:

```ts
dojo.findEntities(...)
...
```

And then generate a namespaced client per project:

```ts
import examples from "dojo_examples";
import other from "other_project";

const moves = examples.models.moves.findMany({
  where: {
    remaining: 0
  }
}

const otherMoves = other.models.moves.findMany({
  where: {
    remaining: 0
  }
}
```

Another approach to consider is the runtime type inference projects like https://github.com/wevm/abitype provide. I haven't looked into it but it seems people prefer this now over generated clients for typescript.

**Comment by Larkooo** [comment]
I think that makes sense and having something similar to abitype would be really nice for typescript users, if we can get a nice typed interface for everything with compile time type checking then it would be really powerful. For eg. if we can leverage typescript at compile time to check if we can query 2 models at once that share the same field (it would throw an error at compile time otherwise, if we try to use a field that isnt present in one of them).

I think it also makes sense to potentially have the state management on the dojo.native side (bindings/dojo.c). Then we could register for callbacks or updates (by abstracting remote calls) to update the state on our side which would be more tailored for the type of sdk we're building. Like for Unity, that state would translate into game objects and components. I'm not sure about the efficiency of that as it would involve having 2 states in some cases but I think it really is the best devX compared to other solutions
