### ISSUE TITLE
[feature] Jotai State integration 

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo.js#168]
Currently dojo has Recs as a state management package, however often this is too heavy.

For simple dapps a state management like Jotai that is synced with torii would be ideal for experimenting.

This tasks is the design a sync and store using https://jotai.org/

The task contains, but not limited to

- [ ] Initial Architecture and design (get review before proceeding)
- [ ] Syncing with Torii using the 'State' package
- [ ] Exposing a setup function for users
- [ ] Building example

**Comment by satyambnsal** [comment]
@ponderingdemocritus Can I pick this issue ?

**Comment by RareSecond** [comment]
I don't agree with this proposal. While I agree Jotai is a great library, we want to keep the `State` package framework agnostic. Our core features should be compatible in a range of frameworks. Our `React` package should be a wrapper around the `State` package (where potentially it could then use Jotai, but don't think that will be needed).

Therefore I've been eyeing Zustand, since it [allows usage outside of React](https://github.com/pmndrs/zustand?tab=readme-ov-file#using-zustand-without-react).

**Comment by ponderingdemocritus** [comment]
Yeah fair point, someone in community could tackle this as I think for simple applications Jotai would be nice.
